<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class PharmacyMedicineSeeder extends Seeder
{
    public function run(): void
    {
        $getGenericId = fn($name) => DB::table('pharmacy_generics')->where('generic_name', 'like', "%{$name}%")->value('id');
        $getCategoryId = fn($name) => DB::table('pharmacy_categories')->where('name', 'like', "%{$name}%")->value('id');
        $getFormId = fn($name) => DB::table('pharmacy_dosage_forms')->where('name', 'like', "%{$name}%")->value('id');
        $getMfrId = fn($name) => DB::table('pharmacy_manufacturers')->where('name', 'like', "%{$name}%")->value('id');
        $getUnitId = fn($name) => DB::table('pharmacy_units')->where('name', 'like', "%{$name}%")->value('id');

        $tabUnit = $getUnitId('Tablet');
        $capUnit = $getUnitId('Capsule');
        $botUnit = $getUnitId('Bottle');
        $boxUnit = $getUnitId('Box');
        $stripUnit = $getUnitId('Strip');
        $vialUnit = $getUnitId('Vial');
        $inhUnit = $getUnitId('Inhaler') ?: $getUnitId('Bottle');

        $tabForm = $getFormId('Tablet');
        $capForm = $getFormId('Capsule');
        $sypForm = $getFormId('Syrup');
        $injForm = $getFormId('Injection');
        $inhForm = $getFormId('Inhaler');

        $analgesicCat = $getCategoryId('Analgesic');
        $antibioticCat = $getCategoryId('Antibiotic');
        $giCat = $getCategoryId('Gastrointestinal');
        $respCat = $getCategoryId('Respiratory');
        $cvCat = $getCategoryId('Cardiovascular');
        $diabetesCat = $getCategoryId('Anti-diabetic') ?: $getCategoryId('Endocrine');

        $medicines = [
            [
                'item_code' => 'MED-26-1001',
                'barcode' => '896400010011',
                'brand_name' => 'Panadol 500mg Tablet',
                'generic_id' => $getGenericId('Paracetamol'),
                'category_id' => $analgesicCat,
                'dosage_form_id' => $tabForm,
                'manufacturer_id' => $getMfrId('GlaxoSmithKline') ?: $getMfrId('GSK'),
                'purchase_unit_id' => $boxUnit,
                'sale_unit_id' => $tabUnit,
                'unit_conversion' => 200,
                'purchase_price' => 700.00,
                'sale_price' => 4.50,
                'mrp' => 4.50,
                'tax_percent' => 0.00,
                'discount_percent' => 5.00,
                'min_reorder_level' => 100,
                'max_stock_level' => 2000,
                'rack_location' => 'Rack A-01',
                'requires_prescription' => false,
                'is_narcotic' => false,
                'is_active' => true,
            ],
            [
                'item_code' => 'MED-26-1002',
                'barcode' => '896400010028',
                'brand_name' => 'Panadol Extra Tablet',
                'generic_id' => $getGenericId('Paracetamol'),
                'category_id' => $analgesicCat,
                'dosage_form_id' => $tabForm,
                'manufacturer_id' => $getMfrId('GlaxoSmithKline') ?: $getMfrId('GSK'),
                'purchase_unit_id' => $boxUnit,
                'sale_unit_id' => $tabUnit,
                'unit_conversion' => 100,
                'purchase_price' => 450.00,
                'sale_price' => 5.50,
                'mrp' => 5.50,
                'tax_percent' => 0.00,
                'discount_percent' => 5.00,
                'min_reorder_level' => 50,
                'max_stock_level' => 1000,
                'rack_location' => 'Rack A-01',
                'requires_prescription' => false,
                'is_narcotic' => false,
                'is_active' => true,
            ],
            [
                'item_code' => 'MED-26-1003',
                'barcode' => '896400010035',
                'brand_name' => 'Augmentin 625mg Tablet',
                'generic_id' => $getGenericId('Amoxicillin + Clavulanic Acid') ?: $getGenericId('Amoxicillin'),
                'category_id' => $antibioticCat,
                'dosage_form_id' => $tabForm,
                'manufacturer_id' => $getMfrId('GlaxoSmithKline') ?: $getMfrId('GSK'),
                'purchase_unit_id' => $boxUnit,
                'sale_unit_id' => $tabUnit,
                'unit_conversion' => 14,
                'purchase_price' => 380.00,
                'sale_price' => 32.00,
                'mrp' => 32.00,
                'tax_percent' => 0.00,
                'discount_percent' => 5.00,
                'min_reorder_level' => 30,
                'max_stock_level' => 500,
                'rack_location' => 'Rack A-04',
                'requires_prescription' => true,
                'is_narcotic' => false,
                'is_active' => true,
            ],
            [
                'item_code' => 'MED-26-1004',
                'barcode' => '896400010042',
                'brand_name' => 'Augmentin 156.25mg/5ml Suspension',
                'generic_id' => $getGenericId('Amoxicillin + Clavulanic Acid') ?: $getGenericId('Amoxicillin'),
                'category_id' => $antibioticCat,
                'dosage_form_id' => $sypForm,
                'manufacturer_id' => $getMfrId('GlaxoSmithKline') ?: $getMfrId('GSK'),
                'purchase_unit_id' => $boxUnit,
                'sale_unit_id' => $botUnit,
                'unit_conversion' => 1,
                'purchase_price' => 175.00,
                'sale_price' => 210.00,
                'mrp' => 210.00,
                'tax_percent' => 0.00,
                'discount_percent' => 5.00,
                'min_reorder_level' => 15,
                'max_stock_level' => 150,
                'rack_location' => 'Rack B-02',
                'requires_prescription' => true,
                'is_narcotic' => false,
                'is_active' => true,
            ],
            [
                'item_code' => 'MED-26-1005',
                'barcode' => '896400010059',
                'brand_name' => 'Brufen 400mg Tablet',
                'generic_id' => $getGenericId('Ibuprofen'),
                'category_id' => $analgesicCat,
                'dosage_form_id' => $tabForm,
                'manufacturer_id' => $getMfrId('Abbott'),
                'purchase_unit_id' => $boxUnit,
                'sale_unit_id' => $tabUnit,
                'unit_conversion' => 250,
                'purchase_price' => 650.00,
                'sale_price' => 3.20,
                'mrp' => 3.20,
                'tax_percent' => 0.00,
                'discount_percent' => 5.00,
                'min_reorder_level' => 50,
                'max_stock_level' => 1500,
                'rack_location' => 'Rack A-02',
                'requires_prescription' => false,
                'is_narcotic' => false,
                'is_active' => true,
            ],
            [
                'item_code' => 'MED-26-1006',
                'barcode' => '896400010066',
                'brand_name' => 'Brufen 100mg/5ml Syrup',
                'generic_id' => $getGenericId('Ibuprofen'),
                'category_id' => $analgesicCat,
                'dosage_form_id' => $sypForm,
                'manufacturer_id' => $getMfrId('Abbott'),
                'purchase_unit_id' => $boxUnit,
                'sale_unit_id' => $botUnit,
                'unit_conversion' => 1,
                'purchase_price' => 85.00,
                'sale_price' => 105.00,
                'mrp' => 105.00,
                'tax_percent' => 0.00,
                'discount_percent' => 5.00,
                'min_reorder_level' => 20,
                'max_stock_level' => 200,
                'rack_location' => 'Rack B-01',
                'requires_prescription' => false,
                'is_narcotic' => false,
                'is_active' => true,
            ],
            [
                'item_code' => 'MED-26-1007',
                'barcode' => '896400010073',
                'brand_name' => 'Risek 20mg Capsule',
                'generic_id' => $getGenericId('Omeprazole'),
                'category_id' => $giCat,
                'dosage_form_id' => $capForm,
                'manufacturer_id' => $getMfrId('Getz Pharma') ?: $getMfrId('Getz'),
                'purchase_unit_id' => $boxUnit,
                'sale_unit_id' => $capUnit,
                'unit_conversion' => 14,
                'purchase_price' => 310.00,
                'sale_price' => 26.50,
                'mrp' => 26.50,
                'tax_percent' => 0.00,
                'discount_percent' => 5.00,
                'min_reorder_level' => 30,
                'max_stock_level' => 400,
                'rack_location' => 'Rack C-05',
                'requires_prescription' => true,
                'is_narcotic' => false,
                'is_active' => true,
            ],
            [
                'item_code' => 'MED-26-1008',
                'barcode' => '896400010080',
                'brand_name' => 'Risek 40mg IV Injection',
                'generic_id' => $getGenericId('Omeprazole'),
                'category_id' => $giCat,
                'dosage_form_id' => $injForm,
                'manufacturer_id' => $getMfrId('Getz Pharma') ?: $getMfrId('Getz'),
                'purchase_unit_id' => $boxUnit,
                'sale_unit_id' => $vialUnit,
                'unit_conversion' => 1,
                'purchase_price' => 340.00,
                'sale_price' => 415.00,
                'mrp' => 415.00,
                'tax_percent' => 0.00,
                'discount_percent' => 5.00,
                'min_reorder_level' => 20,
                'max_stock_level' => 250,
                'rack_location' => 'Rack D-01 (Injections)',
                'requires_prescription' => true,
                'is_narcotic' => false,
                'is_active' => true,
            ],
            [
                'item_code' => 'MED-26-1009',
                'barcode' => '896400010097',
                'brand_name' => 'Flagyl 400mg Tablet',
                'generic_id' => $getGenericId('Metronidazole'),
                'category_id' => $antibioticCat ?: $giCat,
                'dosage_form_id' => $tabForm,
                'manufacturer_id' => $getMfrId('Sanofi'),
                'purchase_unit_id' => $boxUnit,
                'sale_unit_id' => $tabUnit,
                'unit_conversion' => 200,
                'purchase_price' => 580.00,
                'sale_price' => 3.60,
                'mrp' => 3.60,
                'tax_percent' => 0.00,
                'discount_percent' => 5.00,
                'min_reorder_level' => 60,
                'max_stock_level' => 1200,
                'rack_location' => 'Rack A-09',
                'requires_prescription' => true,
                'is_narcotic' => false,
                'is_active' => true,
            ],
            [
                'item_code' => 'MED-26-1010',
                'barcode' => '896400010103',
                'brand_name' => 'Ventolin Inhaler 100mcg',
                'generic_id' => $getGenericId('Salbutamol'),
                'category_id' => $respCat,
                'dosage_form_id' => $inhForm,
                'manufacturer_id' => $getMfrId('GlaxoSmithKline') ?: $getMfrId('GSK'),
                'purchase_unit_id' => $boxUnit,
                'sale_unit_id' => $botUnit,
                'unit_conversion' => 1,
                'purchase_price' => 320.00,
                'sale_price' => 385.00,
                'mrp' => 385.00,
                'tax_percent' => 0.00,
                'discount_percent' => 5.00,
                'min_reorder_level' => 25,
                'max_stock_level' => 200,
                'rack_location' => 'Rack C-01',
                'requires_prescription' => true,
                'is_narcotic' => false,
                'is_active' => true,
            ],
            [
                'item_code' => 'MED-26-1011',
                'barcode' => '896400010110',
                'brand_name' => 'Lipiget 20mg Tablet',
                'generic_id' => $getGenericId('Atorvastatin'),
                'category_id' => $cvCat,
                'dosage_form_id' => $tabForm,
                'manufacturer_id' => $getMfrId('Getz Pharma') ?: $getMfrId('Getz'),
                'purchase_unit_id' => $boxUnit,
                'sale_unit_id' => $tabUnit,
                'unit_conversion' => 10,
                'purchase_price' => 240.00,
                'sale_price' => 29.50,
                'mrp' => 29.50,
                'tax_percent' => 0.00,
                'discount_percent' => 5.00,
                'min_reorder_level' => 20,
                'max_stock_level' => 300,
                'rack_location' => 'Rack E-03',
                'requires_prescription' => true,
                'is_narcotic' => false,
                'is_active' => true,
            ],
            [
                'item_code' => 'MED-26-1012',
                'barcode' => '896400010127',
                'brand_name' => 'Glucophage 500mg Tablet',
                'generic_id' => $getGenericId('Metformin'),
                'category_id' => $diabetesCat,
                'dosage_form_id' => $tabForm,
                'manufacturer_id' => $getMfrId('Searle') ?: $getMfrId('Hilton'),
                'purchase_unit_id' => $boxUnit,
                'sale_unit_id' => $tabUnit,
                'unit_conversion' => 50,
                'purchase_price' => 160.00,
                'sale_price' => 3.80,
                'mrp' => 3.80,
                'tax_percent' => 0.00,
                'discount_percent' => 5.00,
                'min_reorder_level' => 30,
                'max_stock_level' => 500,
                'rack_location' => 'Rack E-06',
                'requires_prescription' => true,
                'is_narcotic' => false,
                'is_active' => true,
            ],
        ];

        foreach ($medicines as $item) {
            $exists = DB::table('pharmacy_medicines')->where('item_code', $item['item_code'])->exists();
            if (!$exists) {
                DB::table('pharmacy_medicines')->insert(array_merge($item, [
                    'id' => (string) Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                ]));
            }
        }
    }
}
